services:
  # APACHE E PHP
  # app1:
  #   image: php:5.5-apache
  #   container_name: app1.apache
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./app1:/var/www/html
  #   networks:
  #     mynetwork:
  #       ipv4_address: 172.16.0.10

  # app2:
  #   image: php:7.4-apache
  #   container_name: app2.apache
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./app2:/var/www/html
  #   networks:
  #     mynetwork:
  #       ipv4_address: 172.16.0.11

  app3-files:
    image: php:5.5.38-fpm
    container_name: app3.files
    working_dir: /var/www/
    volumes:
      - ./app3/files:/var/www/
    networks:
      mynetwork:
        ipv4_address: 172.16.0.13

  app3-nginx:
      image: nginx:alpine
      container_name: app3.nginx
      restart: unless-stopped
      ports:
        - "8082:80"
      volumes:
          - ./app3/files:/var/www
          - ./app3/conf/nginx/:/etc/nginx/conf.d/
          - ./app3/logs:/var/log/nginx/ 
      networks:
        mynetwork:
          ipv4_address: 172.16.0.14

  app4-files:
    image: php:5.6-fpm-alpine
    container_name: app4.files
    working_dir: /var/www/
    volumes:
      - ./app4/files:/var/www/
    networks:
      mynetwork:
        ipv4_address: 172.16.0.15

  app4-nginx:
      image: nginx:alpine
      container_name: app4.nginx
      restart: unless-stopped
      ports:
        - "8083:80"
      volumes:
          - ./app4/files:/var/www
          - ./app4/conf/nginx/:/etc/nginx/conf.d/
          - ./app4/logs:/var/log/nginx/         
      networks:
        mynetwork:
          ipv4_address: 172.16.0.16

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24